apiVersion: v1
kind: Service
metadata:
  name: aws-cicd-demo-service
spec:
  selector:
    app: aws-cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


